
package:
    name: libint
    version: 2.3.1
source:
    fn: libint-2.3.1.tgz
    url: https://github.com/evaleev/libint/releases/download/v2.3.1/libint-2.3.1.tgz
build:
    number: '0'
    run_exports:
        - libint
    string: '0'
requirements:
    build:
        - autoconf 
        - gxx_linux-64
        - m4
        - gcc_impl_linux-64
        - gcc_linux-64
        - libgcc-ng 
        - libtool 
        - ccache 
        - binutils_impl_linux-64
        - libstdcxx-ng 
        - gxx_impl_linux-64
        - binutils_linux-64
    host:
        - eigen 
        - libstdcxx-ng
        - mkl 
        - python 3.7.1
        - libgfortran-ng
        - gmp 
        - boost 
        - libboost
        - wheel 
        - ncurses
        - ca-certificates 
        - libgcc-ng 
        - intel-openmp
        - icu 
        - setuptools
test:
    commands:
        - conda inspect linkages libint
about:
    home: https://github.com/evaleev/libint
    license: LGPL-3.0+
    license_family: LGPL
    license_file: LICENSE
    license_url: https://opensource.org/licenses/LGPL-3.0+
    summary: two-body molecular integrals over Gaussian functions library
extra:
    copy_test_source_files: true
    final: true
